server:
  port: 8080

spring:
  main:
    web-application-type: reactive

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**,/api/users/**

        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/api/restaurants/**

        - id: menu-service
          uri: lb://menu-service
          predicates:
              - Path=/api/menus/**

        - id: cart-service
          uri: lb://cart-service
          predicates:
              - Path=/api/cart/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**



  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: my-secret-key-for-food-app-which-is-very-secure-and-long



logging:
  level:
    org.springframework.cloud.gateway: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

