server:
  port: 8083

spring:

  application:
    name: menu-service

#   datasource:
#     url: jdbc:mysql://localhost:3306/menu_db
#     username: root
#     password: Vinayaga@19

#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true

# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka

# management:
#   tracing:
#     sampling:
#       probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

